### ISSUE TITLE
How to configure it with redmine server?

### ISSUE THREAD

**Issue by alexeyzhuchkov** [gilchris/ConvenientRedmine#2]

**Comment by gilchris** [comment]
Open option page.
After install chrome extension [ConvenientRedmine](https://chrome.google.com/webstore/detail/convenient-redmine/cebgldbppceblpomepllpcmmebbmfcko), click extension default icon(Sorry i have no icon image.) by right side of address bar. and click options.

Change 'Working Domain' and click save.
must write working domain with javascript regular expression.
